### recuperar todas los productos
GET http://localhost:1234/shoes

### Recuperar un producto por id
GET http://localhost:1234/shoes/1808b5de-2cad-4321-9ddb-4fc2d3712449

### Recuperar todas los producto por precio
GET http://localhost:1234/shoes?brand=Nike

### crear un producto con POST
POST http://localhost:1234/shoes
Content-Type: application/json

{
  "product_name": "Nike",
  "brand": "Nike",
  "price": 40.99,
  "size": 34,
  "image": null,
  "category": ["female"],
  "stock": 100
}


### modificar un producto filtrando por id
PATCH http://localhost:1234/shoes/1808b5de-2cad-4321-9ddb-4fc2d3712449
Content-Type: application/json"

{
  "id": "1",
  "input": {
    "product_name": "Nike Air Max",
    "brand": "Nike",
    "price": 120.99,
    "size": 42,
    "image": "nike-air-max.jpg",
    "category": "running"
  }
}
