### recuperar todas las películas

GET http://localhost:1234/shoes

### Recuperar una pelicual
GET http://localhost:1234/shoes/5605f2bb-5407-439a-a70f-7f404300d63c

### Recuperar todas las películas por género
GET http://localhost:1234/shoes?genre=action

### crear una película con POST
POST http://localhost:1234/shoes
Content-Type: application/json

{
  "name": "Jordan",
  "brand": "Nike",
  "price": 40.99,
  "size": 34,
  "image": "",
  "category": ["female"] ,
  "stock": 100
}


### modificar una película filtrando por id
PATCH http://localhost:1234/shoes/5605f2bb-5407-439a-a70f-7f404300d63c
Content-Type: application/json"

{
  "name": "Nuevo título",
  "size": 8
}
